# Minimal Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker-kubetorch-minimal-binding
  namespace: default  # TODO: Use your Kubetorch .to deployment namespace here
  labels:
    app: airflow
    component: worker-permissions
    source-role: kubetorch-role
subjects:
- kind: ServiceAccount
  name: airflow-worker  # TODO: Use your service account name here
  namespace: airflow  # TODO: Use your airflow namespace here
roleRef:
  kind: Role
  name: kubetorch-minimal-role
  apiGroup: rbac.authorization.k8s.io
---
# ConfigMap Reader Role
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-worker-kubetorch-configmap-reader-binding
  namespace: kubetorch
  labels:
    app: airflow
    component: worker-permissions
    source-role: kubetorch-role
subjects:
- kind: ServiceAccount
  name: airflow-worker  # TODO: Use your service account name here
  namespace: airflow  # TODO: Use your airflow namespace here
roleRef:
  kind: Role
  name: kubetorch-configmap-reader
  apiGroup: rbac.authorization.k8s.io
